---
title: "CR Trends of week,hour,date"
output: html_document


params:
  startdate:  'DATE_SUB(CURDATE(), INTERVAL 15 DAY)'                            ## start date for report, interval can be changed if needed
  enddate:    'CURDATE()'                                                       ## end date
  tableName: '`mundiale_tfn.smetable_new2`'                                     ## SME table name
  programID: 'MundialeAYTY_TFN'                                                 ## programID
  
  sme_filter: "skill in ('0024900024') and crm_lookup = 1 and leadlist_lookup = 1 and c_offer_type_CRM = 'PRE_CTRL' and skill is not null and skill <>                 'NA' and tipo_de_ligacao = 'Preditivo' and nconnects_oth2 <> 'NA' and isrelevant = 1"
               #sme filter in addition to callTime. Leave it empyt if there isn't any
  
  variables: "weekday(calltime) weekday,login_ayty agentid,calltime,aht,on_off,issale,c_tmp_base_5_crm,c_qt_durc_trfd_5_crm, case when                 c_qt_durc_trfd_3_crm in (0,1) then 1 else 0 end qt_3_bin_1, case when c_qt_durc_trfd_3_crm in (1,2) then 1 else c_qt_durc_trfd_3_crm  end qt_3_bin_2, case when  c_tmp_base_3_crm in (2,3) then 2 else 1 end tmp_3_bin, m_filler_ll, case when C_TMP_BASE_CRM between 1 and 250 then 1 else 5 end tmp_bin, case when C_TECNOLOGIA_RESUMO_CRM in ('2G','3G') then 1 else 2 end tech_bin,case when C_QT_DURC_TRFD_crm in (0,1) then 1 else 2 end qt_cust, Case when (C_Age_CRM) <= '38' then 1 when (C_Age_CRM) > '38' then 2 end dark_variable_1, case when M_REGIONAL_LL in ('RJ_ES') then 1 when M_REGIONAL_LL in  ('MG','PR_SC') then 2 when M_REGIONAL_LL in ('CO','SP','N','BA_SE')  then 3 when M_REGIONAL_LL in ('NE','RS') then 4 else 0 end m_regional_ll_bin, case when C_sexo_crm= '-3' then 1 else 0 end sex_b, case when cast(nconnectsrollup_oth3 as signed) <= 20 then cast(nconnectsrollup_oth3 as signed) when cast(nconnectsrollup_oth3 as signed) > 50 then 51 else ceiling(( cast(nconnectsrollup_oth3 as signed)/5)) * 5 end nconnectsrollup_bin,                    case when nconnectsrollup_oth3 between 1 and 10 then 1  else 2 end nc_b, M_FIELD_2_LL, m_oferta_ll "  ##enter variables after issale.
             
  time_column: "calltime" 
  optimizationmetric : 'issale'                             # optimization column in sme. All stat are calculated on this.
  
  fileName: "Trends of CR Weekwise,hourwise,datewise"       #Output file name 

  database: "smexplorerdata"                                # Schema on ai server.
  user : 'mundiale_ai_user'
  pass : "#mundiale_ai_user#"
  host : '10.4.2.82'
  port : 3307

---

<style>
pre {U
  overflow-x: auto;
}

tbody tr:nth-child(odd){
    background-color: #F7FBFF;
  }

pre code {
  word-wrap: normal;
  white-space: pre;
}
</style> 


```{r packages4, include=FALSE , warning=FALSE , message=FALSE}
##Loading essential libraries

library(tidyverse)
library(dplyr)
library(DBI)
library(tidyr)
library(RMySQL)
library(data.table)
library(stringr)
library(modelr)
library(scales)
library(knitr)
library(ggplot2)
library(lubridate)
library(randomForest)
library(formattable)
library(rpart)


```




```{r disconnect connections4, include=FALSE , warning=FALSE , message=FALSE}
all_cons <- dbListConnections(MySQL())
# print(all_cons)
for(con in all_cons)
  +  dbDisconnect(con)
```



```{r SmeQuery4 , include=FALSE , echo=FALSE , warning=FALSE , message=FALSE}

SmeQuery <- function(params){
    
    my_query = paste0("select " , params$variables, " from " ,params$tableName,
                      " where ",  params$sme_filter, " and ", params$time_column, " between " ,params$startdate, " and " , params$enddate)
    return(my_query)
  }
```





```{r get_data4 , include=FALSE, echo=FALSE  , warning=FALSE , message=FALSE}

my_query <- SmeQuery(params)

MySQLConnect216AI <- dbConnect(dbDriver("MySQL"),user=params$user, password=params$pass,
                               dbname=params$database, host=params$host, port = params$port)


VARNAME <- dbGetQuery(MySQLConnect216AI, my_query); 

on.exit(dbDisconnect(MySQLConnect216AI))

dist=as.data.frame(VARNAME)

data = dist
setnames(data, tolower(names(data)))

```

# Zero Agents
``` {r zero_agent, echo=FALSE}

#data[is.na(data)] = 0
##data
#ggplot(data=data, aes(x=date, y=offcr, group=1, color = "Off_CR")) +
  #geom_line(color="red")+geom_point() +
#geom_line(data=data, aes(x=date, y=call_perc, group =2, color = "call_perc")) +
  #geom_line(color="green")
 a = data %>% group_by(date = as.Date(calltime)) %>% dplyr::summarise(CR = mean(issale)*100,calls = n())
  b = data %>% group_by(hour = hour(calltime)) %>% dplyr::summarise(CR = mean(issale)*100,calls = n())
 #c=  data %>% group_by(dt = weekdays(calltime)) %>% summarise(CR = mean(issale),calls = n())
  d = data %>% group_by(week = week(calltime)) %>% dplyr::summarise(CR = mean(issale)*100,calls = n())
  e = data %>% group_by(weekday) %>% dplyr::summarise(CR = mean(issale)*100,calls = n())
  
f = data %>% group_by(agentid) %>% dplyr::summarise(CR = mean(issale)*100,calls = n())
f <- as.data.table(f)
ffil <- f[calls > 500 & CR ==0]
##print("Agents takng more than 500 calls and have not made a sale")
##print(ffil$agentid)

if (length(ffil$agentid) == 0){
  kable("There are no zero agents by the provided call threshold.")
} else {
  kable((ffil$agentid),
           caption = "Agents taking more than 500 calls and have not made a sale")
}
```

# CR Trends
**CR Trend Day-wise**
``` {r cr_trend_day, echo=FALSE ,results='asis'}
  formattable(a)
  print(ggplot(data=a, aes(x=date, y=CR)) + geom_bar(stat="identity", fill="#56B4E9"))
```
  
**CR Trends Hour-wise**  
```{r cr_trend_hour, echo=FALSE ,results='asis'}
  formattable(b)
  print(ggplot(data=b, aes(x=hour, y=CR)) + geom_bar(stat="identity", fill="#E69F00"))
```  
  
**CR Trends Week-wise**
```{r cr_trend_week, echo=FALSE ,results='asis'}
  formattable(d)
  print(ggplot(data=d, aes(x=week, y=CR)) + geom_bar(stat="identity", fill="#999999"))
```
 
**CR Trends Weekday-wise** 
``` {r cr_trend_weekday, echo=FALSE ,results='asis'}
  formattable(e)
  print(ggplot(data=e, aes(x=weekday, y=CR)) + geom_bar(stat="identity", fill="#E69F00"))

 
````

## Random Forest

``` {r rand_for, echo = FALSE}
  
use = data[,c(5:length(data))]
  
training = use
callgroup.tree <- rpart(issale ~., data = use, control = rpart.control(minbucket = 500, cp = 0), method = "anova")
min.cp <- callgroup.tree$cptable[which.min(callgroup.tree$cptable[,"xerror"]), "CP"]
callgroup.tree <- prune(callgroup.tree, cp = min.cp)
##print('Variable Imporatance due to RParts')


training = use

##make nulls NA
is.na(training) <- is.null(training)

## clean data of all NAs
data_lm <- as.data.frame(training)
data_lm[is.na(data_lm)] <- "NA"

## make var factors
data_lm <- lapply(data_lm,factor)

## extract num of distinct values of each factor
datalvls=sapply(data_lm, nlevels)


##print and note factors with <2 number of levels
var_to_remove=c()
for (i in 1:length(data_lm)){ 
  if ( datalvls[i]<2)
    {
  var_to_remove = append(var_to_remove, i)
    }
}
## remove factors that passed previous conditions
#data_lm <- data_lm[-var_to_remove]
rm(var_to_remove)

##print and note factors with >53 number of levels
var_to_remove=c()
datalvls=sapply(data_lm, nlevels)
for (i in 1:length(data_lm)){ 
  if (datalvls[i]>53 ){
  var_to_remove = append(var_to_remove, i)
}
}
## remove factors that passed previous conditions
#data_lm <- data_lm[-var_to_remove]
rm(var_to_remove)

## random Forest
fit_lm = randomForest(issale~., data=data_lm,na.action=na.exclude)

##Forest importance with vars less than 53 values


imp = as.data.frame(fit_lm$importance)
imp$variable=row.names(fit_lm$importance)
imp <- data.frame(imp$variable,imp$MeanDecreaseGini)
colnames(imp) <- c("varaible","rand_forest_importance")
imp <- formattable(imp, list(area(col = rand_forest_importance ) ~ color_tile("transparent", "pink")))
imp[order(-imp$rand_forest_importance),]

#print(data)
#geom_point()





##ggplot(data=data, aes(x=date, y=offcr)) +
 ## geom_line() + geom_point()+
##  scale_color_brewer(palette="Paired")+
  ##theme_minimal() 


##ggplot(data,aes(date,offcr,color="Off_CR")+geom_line(color="Off_CR")+
  ##geom_line(data,aes(date,call_perc,color="Second line"))
```

## R-Parts

``` {r rpart, echo = FALSE}

kable(callgroup.tree$variable.importance, col.names = c("r-parts importance"))

```