---
title: "Pre-Modelling Check Dashboard"
site: bookdown::bookdown_site

output:
  bookdown::html_document2
  

---



```{r hook-def, include=FALSE}
params_cache <- new.env(parent = emptyenv())
knitr::knit_hooks$set(use.params = function(before, options, envir) {
  if (before && options$use.params) {
    if (exists("params", envir = envir)) {
      params_cache$params <- envir$params
    }
    text <- readLines(knitr::current_input(dir = TRUE))
    knit_params <- knitr::knit_params(text)
    envir$params <- purrr::map(knit_params, "value")
  }
  if (!before && options$use.params) {
    if (exists("params", envir = params_cache)) {
      envir$params <- params_cache$params
      rm("params", envir = params_cache)
    } else {
      rm("params", envir = envir)
    }
  }
})
```


```{r child = 'var_analysis.Rmd', use.params=TRUE, results='asis', fig.align='center'}
```


```{r child = 'corr_mat.Rmd', use.params=TRUE, results='asis', fig.align='center'}
```


```{r child = 'unknown_Agent.Rmd', use.params=TRUE, results='asis', fig.align='center'}
```


```{r child = 'corrGKT.Rmd', use.params=TRUE, results='asis', fig.align='center'}
```


```{r child = 'rand_fore.Rmd', use.params=TRUE, fig.align='center', results='asis'}
```
