---
title: "Variable Analysis"
output: html_document


params:
  startdate:  'DATE_SUB(CURDATE(), INTERVAL 75 DAY)'                             ##start date for report, interval can be changed if needed
  enddate: 'CURDATE()'                                                           ##end date
  tableName: '`mundiale_tfn.smetable_new2`'                                      ##table name
  programID: 'MundialeAYTY_TFN'                                                  ##programID
  
  
  #sme filter for inscope calls in without callTime. Leave it empyt if there isn't any
  sme_filter: "skill in ('0024900024') and crm_lookup = 1 and leadlist_lookup = 1 and c_offer_type_CRM = 'PRE_CTRL' and skill is not null and on_off = 0 and skill <> 'NA' and tipo_de_ligacao = 'Preditivo' and nconnects_oth2 <> 'NA' and isrelevant = 1 and isweekday = 1"
               
  
  ##add variables for which the analysis needs to be performed, also change is_analysis parameter accordingly             
  
  variables: "c_qt_durc_trfd_3_crm, c_qt_durc_trfd_5_crm, c_tmp_base_3_crm, c_tmp_base_5_crm, case when c_qt_durc_trfd_3_crm in (0,1) then 1 else 0 end qt_3_bin_1,                     case when c_qt_durc_trfd_3_crm in (1,2) then 1 else c_qt_durc_trfd_3_crm  end qt_3_bin_2, case when  c_tmp_base_3_crm in (2,3) then 2 else 1 end tmp_3_bin,               m_filler_ll, case when C_TMP_BASE_CRM between 1 and 250 then 1 else 5 end tmp_bin, case when C_TECNOLOGIA_RESUMO_CRM in ('2G','3G') then 1 else 2 end tech_bin,     case when C_QT_DURC_TRFD_crm in (0,1) then 1 else 2 end qt_cust, Case when (C_Age_CRM) <= '38' then 1 when (C_Age_CRM) > '38' then 2 end dark_variable_1,                 case when M_REGIONAL_LL in ('RJ_ES') then 1 when M_REGIONAL_LL in  ('MG','PR_SC') then 2 when M_REGIONAL_LL in ('CO','SP','N','BA_SE')  then 3 when                       M_REGIONAL_LL in ('NE','RS') then 4 else 0 end m_regional_ll_bin, case when C_sexo_crm= '-3' then 1 else 0 end sex_b,                                                     case when cast(nconnectsrollup_oth3 as signed) <= 20 then cast(nconnectsrollup_oth3 as signed) when cast(nconnectsrollup_oth3 as signed) > 50 then 51 else                ceiling(( cast(nconnectsrollup_oth3 as signed)/5)) * 5 end nconnectsrollup_bin,                                                                                           case when nconnectsrollup_oth3 between 1 and 10 then 1  else 2 end nc_b, M_FIELD_2_LL, m_oferta_ll, m_freshbau,(case when C_QT_DURC_TRFD_crm in (0,1) then 1 else 2 end) /(case when  c_tmp_base_3_crm in (2,3) then 2 else 1 end) cust_qt_tmp, on_off,agentpercentile AP," 
  
  ##all the variables that are included in analysis will be marked true, position matters.
  
  is_analysis: ["T","T","T","T","T","T","T","T","T","T","T","T","T","T","T","T","T","T","T","T","F","F"] 

  conslidation_period: "date"   ##enter consolidation period week/date/month etc.
  time_column: "calltime" 
  optimizationmetric : 'issale' # optimization column in sme. All stat are calculated on this.
  
  fileName: "0024900024_Mundiale_Variable_Analysis" #Output file name 

  database: "smexplorerdata" # Schema on ai server.
  user : 'mundiale_ai_user'
  pass : "#mundiale_ai_user#"
  host : '10.4.2.82'
  port : 3307
---


```{r packages1, include=FALSE , warning=FALSE , message=FALSE}
##Loading essential libraries


library(dplyr)
library(RMySQL)
library(data.table)
library(knitr)
library(ggplot2)
library(lubridate)


```


```{r disconnect connections1, include=FALSE , warning=FALSE , message=FALSE}
all_cons <- dbListConnections(MySQL())
# print(all_cons)
for(con in all_cons)
  +  dbDisconnect(con)
```


```{r SmeQuery1 , include=FALSE , echo=FALSE , warning=FALSE , message=FALSE}

SmeQuery <- function(params){
    
    my_query = paste0("select ", params$conslidation_period, "(" , params$time_column, ") as ", params$conslidation_period, ", " , params$variables, params$optimizationmetric, " from "                                ,params$tableName, " where ",  params$sme_filter, " and ", params$time_column, " between " ,params$startdate, " and " , params$enddate)
    return(my_query)
}
```




```{r get_data1 , include=FALSE, echo=FALSE  , warning=FALSE , message=FALSE}

my_query <- SmeQuery(params)

MySQLConnect216AI <- dbConnect(dbDriver("MySQL"),user=params$user, password=params$pass,
                               dbname=params$database, host=params$host, port = params$port)


VARNAME <- dbGetQuery(MySQLConnect216AI, my_query); 

on.exit(dbDisconnect(MySQLConnect216AI))

dist=as.data.frame(VARNAME)

data = dist
setnames(data, tolower(names(data)))

```

# Variable Analysis
``` {r visualization1, echo = FALSE ,  message=FALSE , warning=FALSE}

is_analysis =  as.logical(as.vector(unlist(params$is_analysis))) 
##is_var = c("c_qt_durc_trfd_3_crm", "c_tmp_base_3_crm", "m_filler_ll")

for (i in 1:(length(is_analysis)-2)){
  data[[i+1]] = as.character(unlist(data[[i+1]]))
}

if (params$conslidation_period == 'date'){
  data$date = ymd(data$date)
}


for (i in 1:(length(is_analysis)-2)){
  x <- params$conslidation_period
  y <- colnames(data)[[1+i]]
  data1 <- data %>% group_by_(x,y) %>% summarise(off_cr = mean(issale))
  data2 <- data  %>% group_by_(x,y) %>%  count(, name='total_calls_off')
  data3 <- left_join(data1,data2)
  z <- colnames(data3)[[3]]
  a <- colnames(data3)[[4]]
  
  
  data4 <- data
  data4 <- data4 %>% filter(!(is.na(ap)))
  data4[data4$ap > 0.5, ]$ap = 2
  data4[data4$ap <= 0.5, ]$ap = 1

  data5 <- data4 %>% filter(ap == 1) %>% group_by_(x,y) %>% summarise(CR_1 = mean(issale))
  data6 <- data4  %>% filter(ap == 2) %>% group_by_(x,y) %>% summarise(CR_2 = mean(issale))
  data7 <- left_join(data5,data6)
  data7$VA <- data7$CR_2 - data7$CR_1

  u <- colnames(data7)[[5]]
  
  
  plot1 <- ggplot(data3, aes_(x = as.name(x) , y = as.name(z))) + 
  geom_line(aes_(color = as.name(y)) , size =1) +
  geom_point(size = 1.5) +  scale_color_brewer(palette="Set1") + theme(legend.position="top")
  
  plot2 <- ggplot(data7, aes_(x = as.name(x) , y = as.name(u))) +
  geom_line(aes_(color = as.name(y)) , size =1) +
  geom_point(size = 0.1) +  scale_color_brewer(palette="Set1") + theme(legend.position="top")
  
  plot3 <- ggplot(data3, aes_(x = as.name(x) , y = as.name(a))) + 
  geom_line(aes_(color = as.name(y)) , size =1) +
  geom_point(size = 0.1) +  scale_color_brewer(palette="Set1") + theme(legend.position="top")
  
   
  # grid.arrange(plot1, plot2, ncol=2,  widths = c(3,3) )
  
  print(plot1)
  print(plot2)
  print(plot3)
}


##data1 <- data %>% group_by(week,c_qt_durc_trfd_3_crm) %>% summarise(off_cr = mean(issale)) 
##data2 <- data  %>% group_by(week,c_qt_durc_trfd_3_crm) %>%  count(, name='total_calls')
##data3 <- left_join(data1,data2)
##ggplot(data3, aes(x = week, y = off_cr)) + 
  ##geom_line(aes(color = c_qt_durc_trfd_3_crm) , size =2) + geom_point(size = 3) +  scale_color_brewer(palette="Set1")
  ##theme_ipsum()

##x <- colnames(data)[[1]]
 ## y <- colnames(data)[[2]]
 ## data1 <- data %>% group_by_(is_var[1],is_var[2]) %>% summarise(off_cr = mean(issale))

  ##is_var[1]
##colnames(data3)

##head(data3,6)



 
```