---
title: "Variable Analysis"
output: html_document


params:
  startdate:  'DATE_SUB(CURDATE(), INTERVAL 3 MONTH)'                            ##start date for report, interval can be changed if needed
  enddate: 'CURDATE()'                                                           ##end date
  tableName: ''                                      ##table name
  programID: ''                                                  ##programID
  
  sme_filter: ""
               #sme filter in addition to callTime. Leave it empyt if there isn't any
  
  variables: "" ##add variables for which the correlation needs to be checked
  conslidation_period: "month"   ##enter consolidation period week/date/month etc.
  time_column: "calltime" 
  optimizationmetric : '' # optimization column in sme. All stat are calculated on this.
  
  fileName: "Variable_Analysis" #Output file name 

  database: "" # Schema on ai server.
  user : ''
  pass : ""
  host : ''
  port : 
---


```{r packages, include=FALSE , warning=FALSE , message=FALSE}
##Loading essential libraries

library(tidyverse)
library(dplyr)
library(DBI)
library(tidyr)
library(RMySQL)
library(data.table)
library(stringr)
library(modelr)
library(scales)
library(knitr)
library(ggplot2)
library(lubridate)
library(hrbrthemes)

```


```{r disconnect connections, include=FALSE , warning=FALSE , message=FALSE}
all_cons <- dbListConnections(MySQL())
# print(all_cons)
for(con in all_cons)
  +  dbDisconnect(con)
```


```{r SmeQuery , include=FALSE , echo=FALSE , warning=FALSE , message=FALSE}

SmeQuery <- function(params){
    
    my_query = paste0("select ", params$conslidation_period, "(" , params$time_column, ") as ", params$conslidation_period, ", " , params$variables, params$optimizationmetric, " from "                                ,params$tableName, " where ",  params$sme_filter, " and ", params$time_column, " between " ,params$startdate, " and " , params$enddate)
    return(my_query)
}
```




```{r get_data , include=FALSE, echo=FALSE  , warning=FALSE , message=FALSE}

my_query <- SmeQuery(params)

MySQLConnect216AI <- dbConnect(dbDriver("MySQL"),user=params$user, password=params$pass,
                               dbname=params$database, host=params$host, port = params$port)


VARNAME <- dbGetQuery(MySQLConnect216AI, my_query); 

on.exit(dbDisconnect(MySQLConnect216AI))

dist=as.data.frame(VARNAME)

data = dist
setnames(data, tolower(names(data)))

```


``` {r visualization, echo = FALSE ,  message=FALSE , warning=FALSE}

is_analysis = c(T,T,T) ## the variables that would be included in analysis will be marked true
is_var = c("c_qt_durc_trfd_3_crm", "c_tmp_base_3_crm", "m_filler_ll")



for (i in 1:(length(is_analysis))){
  x <- params$conslidation_period
  y <- colnames(data)[[1+i]]
  data1 <- data %>% group_by_(x,y) %>% summarise(off_cr = mean(issale))
  data2 <- data  %>% group_by_(x,y) %>%  count(, name='total_calls_off')
  data3 <- left_join(data1,data2)
  z <- colnames(data3)[[3]]
  a <- colnames(data3)[[4]]
  
  plot1 <- ggplot(data3, aes_(x = as.name(x) , y = as.name(z))) + 
  geom_line(aes_(color = as.name(y)) , size =1) +
  geom_point(size = 3) +  scale_color_brewer(palette="Set1")
  
  plot2 <- ggplot(data3, aes_(x = as.name(x) , y = as.name(a))) + 
  geom_line(aes_(color = as.name(y)) , size =1) +
  geom_point(size = 3) +  scale_color_brewer(palette="Set1")
  
  print(plot1)
  print(plot2)
}


##data1 <- data %>% group_by(week,c_qt_durc_trfd_3_crm) %>% summarise(off_cr = mean(issale)) 
##data2 <- data  %>% group_by(week,c_qt_durc_trfd_3_crm) %>%  count(, name='total_calls')
##data3 <- left_join(data1,data2)
##ggplot(data3, aes(x = week, y = off_cr)) + 
  ##geom_line(aes(color = c_qt_durc_trfd_3_crm) , size =2) + geom_point(size = 3) +  scale_color_brewer(palette="Set1")
  ##theme_ipsum()

##x <- colnames(data)[[1]]
 ## y <- colnames(data)[[2]]
 ## data1 <- data %>% group_by_(is_var[1],is_var[2]) %>% summarise(off_cr = mean(issale))

  ##is_var[1]
##colnames(data3)

##head(data3,6)


```